### PR TITLE
refactor: Convert actix-web extractors to async

### PR DESCRIPTION
**Pull request by Emmanuel-Melon**
## Description

This change converts the following actix-web extractors from Futures style to async await
- BsoBodies::from_request
- BsoBody::from_request
- BsoPutRequest::from_request
- ConfigRequest::from_request
- HeartbeatRequest::from_request

## Testing

Running `cargo test`

## Issue(s)

Closes [544](https://github.com/mozilla-services/syncstorage-rs/issues/544).

### CODE REVIEW

**Comment by tublitzed** [comment]
Hey @Emmanuel-Melon since this has been open for awhile with no activity I'm going to go ahead and close for now. If you want to re-open it for a review, we'd definitely be happy to take a look.

**Comment by fzzzy** [comment]
I'm going to pick this code up and try to get it landed.

**Comment by tublitzed** [comment]
@fzzzy let's close this an re-open when it's ready for a review.

**Comment by fzzzy** [comment]
Sure.

**Pull request closed without merging**
