### PR TITLE
refactor: Remove python dependency from the dockerfile.

### LINKED ISSUE #567: Remove python dependency
Now that [purge_ttl is in Rust](https://github.com/mozilla-services/syncstorage-rs/issues/385) we should be able to kill the python dep for this codebase.

### PR DESCRIPTION
**Pull request by fzzzy**
## Description

Now that purge_ttl has been ported to rust, we may remove the python dependency from the dockerfile.

## Testing

Tests should pass.

## Issue(s)

Fixes #567

### CODE REVIEW

**Comment by pjenvey** [comment]
We can't remove the Python version until the Rust version is at least on par with the Python version it lacking retrys on ABORTED should be addressed first: https://bugzilla.mozilla.org/show_bug.cgi?id=1626707

**Comment by fzzzy** [comment]
@pjenvey We have both that bugzilla bug and this github bug to track improving the rust script until it works, is that ok? I plan on trying to get it done in the next few days. I can work on retry on ABORTED there if that's ok with you.

https://github.com/mozilla-services/syncstorage-rs/issues/570

**Comment by fzzzy** [comment]
Ok, I'm going to work on retry on ABORTED in this pr.

**Comment by fzzzy** [comment]
Well, we're already using the rust version now, so we'll work on ABORTED in the linked issue.

**Pull request merged**
