### PR TITLE
feat: update to actix-web 3

### LINKED ISSUE #832: Update to actix-web 3
actix-web is now at 3.0.2 and has a couple potential improvements we'd like to have sooner rather than later:

- back pressure improvements: https://github.com/actix/actix-web/issues/1117
- request bodies allocate extremely large buffers: https://github.com/actix/actix-web/issues/1551 (could this be related to #821?)

### PR DESCRIPTION
**Pull request by pjenvey**
## Testing

All tests pass + load testing looks good

## Issue(s)

Closes #832

### CODE REVIEW

**Review by jrconlin — APPROVED** [review]
Aside from the fun with clippy 👍

**Review by jrconlin — APPROVED** [review]

**Comment by jrconlin** [comment]
yeah, from what we've seen not getting state is pretty rare. I'm fine with `.expect()` for those cases.

**Comment by pjenvey** [comment]
> yeah, from what we've seen not getting state is pretty rare. I'm fine with `.expect()` for those cases.

And non-recoverable (a sign the actix app is setup wrong) so panicing makes a lot of sense for convenience sake. My bad for not doing it this way from the beginning

**Comment by jrconlin** [comment]
Going to land this, and merge into mine.

**Pull request merged**
