### PR TITLE
refactor: Convert misc actix-web frontend calls to async await 

### PR DESCRIPTION
**Pull request by Emmanuel-Melon**
## Description

Convert actix-web front-end calls from Futures style into async/await style.

## Testing

How should reviewers test?
This patch doesn't change any behavior and running `cargo test` should pass all tests.

## Issue(s)
#541, #439
Closes [#541](https://github.com/mozilla-services/syncstorage-rs/issues/541).

### CODE REVIEW

**Comment by fzzzy** [comment]
@Emmanuel-Melon This looks good. Can you please run `cargo fmt` on the branch and commit and push the result.

**Comment by Emmanuel-Melon** [comment]
> @Emmanuel-Melon This looks good. Can you please run `cargo fmt` on the branch and commit and push the result.

Just did, The CI is still failing. I'll try digging into the source of error and probably squash these commits afterwards.

**Comment by fzzzy** [comment]
Change the code that the lint is complaining about to this:

    Ok(HttpResponse::Ok().json(meta.db.delete_storage(meta.user_id).await?))

Can you also squash this? Looking good now.

**Comment by Emmanuel-Melon** [comment]
> Change the code that the lint is complaining about to this:
> 
> ```
> Ok(HttpResponse::Ok().json(meta.db.delete_storage(meta.user_id).await?))
> ```
> 
> Can you also squash this? Looking good now.

Thank you, it worked! I'll now squash and then push.

**Pull request merged**
