### PR TITLE
docs: Update instructions for running via Docker

### PR DESCRIPTION
**Pull request by Emmanuel-Melon**
## Description

Update the "Running via Docker" section in README.md because the `mozilla-rust-sdk` has been vendored into this repo thus changing its installation requirements.

## Testing

Work-In-Progress. 

## Issue(s)

Closes [#546](https://github.com/mozilla-services/syncstorage-rs/issues/546).

### CODE REVIEW

**Comment by jrconlin** [comment]
Looks like this will need to be signed.

**Comment by Emmanuel-Melon** [comment]
> Looks like this will need to be signed.

You mean the first two commits?

**Comment by jrconlin** [comment]
Huh, github was complaining that the patch couldn't land because it wasn't signed, not sure what happened. I'm rebasing now to bring it up-to-date.

**Comment by tublitzed** [comment]
@Emmanuel-Melon yeah, I think it is the first two commits. If you squash and force push you should be fine.

**Comment by Emmanuel-Melon** [comment]
> @Emmanuel-Melon yeah, I think it is the first two commits. If you squash and force push you should be fine.

It's weird how those two commits keep on appearing in every PR that I make.

**Comment by fzzzy** [comment]
@Emmanuel-Melon Make sure you switch back to master before you make any new branch. Check with git log -1 that the head of master is the same as the commit hash you see on the mozilla-services version of master. If not, use `git reset --hard [commit hash you see on the github mozilla services master tip]` before making your branch.

`git stash` may be useful during this process to save your current changes, switch back to and clean up master, then make a new branch and git stash pop.

**Comment by fzzzy** [comment]
Github is still complaining about unsigned commits in this.

**Comment by jrconlin** [comment]
I'm going to dup this PR and submit it on Eman's behalf.

**Comment by jrconlin** [comment]
Closing in favor of #624 which should resolve signed commit blockage.

**Pull request closed without merging**
