### PR TITLE
fix: upgrade to latest deadpool

### PR DESCRIPTION
**Pull request by pjenvey**
which includes a fix for its incorrect metrics:

https://github.com/bikeshedder/deadpool/issues/92

Closes SYNC-4522

### CODE REVIEW

**Review by taddes — DISMISSED** [review]
👍

**Review by jrconlin — DISMISSED** [review]

**Review by taddes — DISMISSED** [review]
All good 👍

**Comment by jrconlin** [comment]
Sigh, yeah, we might want to back-burner this for a while. Looks like there's a number of significant changes in the main version.

**Comment by pjenvey** [comment]
> Sigh, yeah, we might want to back-burner this for a while. Looks like there's a number of significant changes in the main version.

It's not too bad, I've made all the changes (sorry, earlier I forgot to build locally with `--features spanner`)

**Review by jrconlin — APPROVED** [review]

**Pull request merged**
