### PR TITLE
chore: improve local logging

### PR DESCRIPTION
**Pull request by tublitzed**
## Description
 
While working on [this issue](https://github.com/mozilla-services/services-engineering/issues/21), I found out how to do this, which helps a TON when working locally. Since it'll be awhile before I get a PR open for that one, figured I'd get this in now to help anyone else out who might find enabling this by default to be useful.

## Testing

1. Add this new setting to your local `config/local.toml` file. (Checkout the updated README since the instructions for working this way just merged)
2. now `make run-local`
3. You should see colorized and nicely formatted logs instead of everything shoved onto single line in same color.

## Issue(s)

Closes [#350](https://github.com/mozilla-services/syncstorage-rs/issues/350).

### CODE REVIEW

**Comment by jrconlin** [comment]
heh, `human_logs` strikes again.

Might want to put a descriptive comment on this since it impacts logging, and we should default to dumping logs in moz_json format.

**Comment by tublitzed** [comment]
@jrconlin we do default to jumping logs in moz_json format for all envs that are not local. This doesn't change anything that's deployed; this file is only used for local dev.

**Comment by tublitzed** [comment]
@jrconlin do you know of anywhere we document `moz_json` formatting?

**Comment by jrconlin** [comment]
@tublitzed moz_json is part of [the security checklist](https://github.com/mozilla-services/syncstorage-rs/issues/198), and is specified on [the mana page](https://mana.mozilla.org/wiki/display/SVCOPS/Stackdriver+Logging+for+AWS), fortunately, [`slog-mozlog-json`](https://github.com/mozilla-services/slog-mozlog-json) handles the conversion and formatting. 

good point about this only being local. Just want to make sure we don't get hit by the logging error we had previously.

**Pull request merged**
