### PR TITLE
ci: add rust dependency diff

### PR DESCRIPTION
**Pull request by g-k**
refs: https://github.com/mozilla-services/find-package-rugaru/issues/69

### CODE REVIEW

**Comment by g-k** [comment]
Still WIP, but taking out of draft to see if that kicks off CI.

**Comment by g-k** [comment]
I think I need write access to this repo to kick off CircleCI jobs.

@jrconlin or @pjenvey can either of you grant me write access to test this PR out when you get a minute?

**Comment by pjenvey** [comment]
@g-k done, you might need another force push to kick it off

**Comment by g-k** [comment]
Sweet thanks PJ!

**Comment by g-k** [comment]
Replaced by #204

**Pull request closed without merging**
